include: package:very_good_analysis/analysis_options.6.0.0.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    [build/**, lib/**.freezed.dart, lib/**.g.dart, lib/firebase_options.dart]

dart_code_metrics:
  anti-patterns:
    - long-method: false
    - long-parameter-list: false
  metrics-exclude:
    - lib/**.freezed.dart
    - lib/**.g.dart
    - lib/firebase_options.dart
  rules:
    - avoid-global-state: false
    - avoid-returning-widgets: false
    - prefer-moving-to-variable: false
    - avoid-non-null-assertion: false
    - prefer-correct-identifier-length: false
    - no-magic-number: false
    - format-comment: false

linter:
  rules:
    lines_longer_than_80_chars: ignore
    avoid_catches_without_on_clauses: false
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_annotating_with_dynamic: true
