name: multiplayer_firebase_sample
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  chat_bubbles: ^1.5.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0  
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.1
  firebase_database: ^11.1.3
  flutter_bloc: ^8.1.6
  get_it: ^8.0.3
  go_router: ^14.2.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.10+1
  logger: ^2.4.0
  typewrite_text: ^1.0.3
  collection: ^1.19.0
  google_generative_ai: ^0.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.7.0
  go_router_builder: ^2.7.1
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/svg/

flutter_gen:
  line_length: 150
  integrations:
    flutter_svg: true
  assets:
    enabled: true

  colors:
    inputs:
      - assets/color/colors.xml
    outputs:
      class_name: AppColors
